### ISSUE TITLE
[REQ] Upstream Code Sync

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [DJATOM/x264-aMod-patches#11]
Heya, huge fan of your work!

If you don't mind, could you please make an update w/ the latest changes for non tech-savvy bois like me? Thank you kindly, and much love.

**Comment by DJATOM** [comment]
I did sync it recently. I can't throw my job and sync again right now. Maybe on weekend...

**Comment by DJATOM** [comment]
Done.

**Comment by DestroyTargetNonBasicLand** [comment]
Oh my apologies, what I meant to say was if you could make new builds with all the recent changes, similar to your x265 mod (https://github.com/DJATOM/x265-aMod/releases/tag/3.5%2B67) as I have no clue on how to compile these myself.. Sorry about the misunderstanding.

**Comment by DJATOM** [comment]
Ah, ok. It will take some time tho.

**Comment by DJATOM** [comment]
Done.

**Comment by DestroyTargetNonBasicLand** [comment]
Thank you dearly my friend, you're the best!
