### ISSUE TITLE
Why -- bframes is set to -- bframes 2? The GOP value has changed, min = 23, min = 3. I originally set the GOP value to max = 24, min = 1. So why?

### ISSUE THREAD

**Issue by KSSW** [DJATOM/x264-aMod-patches#7]
Why -- bframes is set to -- bframes 2? The GOP value has changed, min = 23, min = 3. I originally set the GOP value to max = 24, min = 1. So why?

x264 Version 18

Video:https://youtu.be/ZHwSh68daSM

**Comment by DJATOM** [comment]
Ask original developers of x264, I'm just providing my patchworks here.

**Comment by KSSW** [comment]
@DJATOM OK

**Comment by KSSW** [comment]
OK,&nbsp;I&nbsp;have&nbsp;solved&nbsp;this&nbsp;problem.


---Original---
From: ***@***.***&gt;
Date: Sat, Sep 25, 2021 14:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DJATOM/x264-aMod] Why -- bframes is set to -- bframes 2? The GOP value has changed, min = 23, min = 3. I originally set the GOP value to max = 24, min = 1. So why? (#7)




 
Ask original developers of x264, I'm just providing my patchworks here.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
